/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sire.sri.batch.autorizacion.constant;

/**
 *
 * @author pestupinan
 */
public class AutorizacionConstant {

    public static String FACTURA_SQL = "SELECT COD_EMPRESA, RUC_EMPRESA, RAZON_SOCIAL_EMPRESA, "
            + "NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_FACTURA_INTERNO, ESTABLECIMIENTO, "
            + "PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, DIRECCION_ESTABLECIMIENTO, "
            + "CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RAZON_SOCIAL_COMPRADOR, "
            + "FECHA_FACTURA, TIPO_IDENTIFICACION_COMPRADOR, IDENTIFICACION_COMPRADOR, "
            + "DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, EMAIL_COMPRADOR, "
            + "TOTAL_SIN_IMPUESTOS, TOTAL_DESCUENTOS, PROPINA, IMPORTE_TOTAL, "
            + "CLAVE_ACCESO, CODIGO_IMPUESTO, CODIGO_PORCENTAJE, BASE_IMPONIBLE, "
            + "VALOR, MONEDA, OBSERVACION FROM V_FACTURA_ELECTRONICA_C WHERE "
            + "CLAVE_ACCESO_LOTE = 'claveAccesoLote' AND "
            + "(ESTADO_SRI='RECIBIDA' OR ESTADO_SRI='EN PROCESAMIENTO') ";

    public static String RETENCION_SQL = "SELECT COD_EMPRESA, RUC_EMPRESA, RAZON_SOCIAL_EMPRESA, "
            + "NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_RETENCION_INTERNO, CLAVE_ACCESO, "
            + "ESTABLECIMIENTO, PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, "
            + "RAZON_SOCIAL_SUJETO_RETENIDO, DIRECCION_RETENIDO, TELEFONO_RETENIDO, "
            + "EMAIL_RETENIDO, FECHA_RETENCION, TIPO_IDENT_SUJETO_RETENIDO, "
            + "IDENTIFICACION_SUJETO_RETENIDO, PERIODO_FISCAL, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE FROM V_RETENCION_ELECTRONICA_C WHERE "
            + "CLAVE_ACCESO_LOTE = 'claveAccesoLote' AND "
            + "(ESTADO_SRI='RECIBIDA' OR ESTADO_SRI='EN PROCESAMIENTO') ";

    public static String NOTA_CREDITO_SQL = "SELECT COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_FACTURA_INTERNO, "
            + "CLAVE_ACCESO, ESTABLECIMIENTO, PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RISE, "
            + "RAZON_SOCIAL_COMPRADOR, DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, "
            + "EMAIL_COMPRADOR, OBSERVACION, FECHA_EMISION, TIPO_IDENTIFICACION_COMPRADOR, "
            + "IDENTIFICACION_COMPRADOR, COD_DOC_MODIFICADO, NUM_DOC_MODIFICADO, "
            + "FECHA_EMISION_DOCSUSTENTO, VALOR_MODIFICADO, TOTAL_SIN_IMPUESTOS, "
            + "MOTIVO, TOTAL_DESCUENTOS, PROPINA, IMPORTE_TOTAL, CODIGO_IMPUESTO, "
            + "CODIGO_PORCENTAJE, BASE_IMPONIBLE, VALOR, MONEDA, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE FROM V_NOTA_CREDITO_ELECTRONICA_C WHERE "
            + "CLAVE_ACCESO_LOTE = 'claveAccesoLote' AND "
            + "(ESTADO_SRI='RECIBIDA' OR ESTADO_SRI='EN PROCESAMIENTO') ";

    public static String NOTA_DEBITO;

    public static String GUIA_REMISION_SQL = "SELECT COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, "
            + "NUM_DESPACHO_INTERNO, CLAVE_ACCESO, ESTABLECIMIENTO, "
            + "PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, DIRECCION_ESTABLECIMIENTO, "
            + "CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RAZON_SOCIAL_TRANSPORTISTA, "
            + "TIPO_IDENT_TRANSPORTISTA, RUC_TRANSPORTISTA, RISE, DIR_PARTIDA, "
            + "FECHA_INICIO_TRANSPORTE, FECHA_FIN_TRANSPORTE, PLACA, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE FROM V_GUIA_REMISION_ELECTRONICA_C WHERE "
            + "CLAVE_ACCESO_LOTE = 'claveAccesoLote' AND "
            + "(ESTADO_SRI='RECIBIDA' OR ESTADO_SRI='EN PROCESAMIENTO') ";
}
