/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sire.sri.batch.constant;

/**
 *
 * @author pestupinan
 */
public class Constant {

    public static final String EMAIL = "Email";
    public static final String MICROSOFT_SQL_SERVER = "Microsoft SQL Server";
    public static final String MYSQL = "MySQL";
    public static final String ORACLE = "Oracle";
    public static final String TIPO_COMPROBANTE = "tipoComprobante";
    public static final String COMPROBANTE = "comprobante";
    public static final String SIRE_HOME = "sire.home";
    public static final String CERO_UNO = "01";
    public static final String CERO_CUATRO = "04";
    public static final String CERO_CINCO = "05";
    public static final String CERO_SEIS = "06";
    public static final String CERO_SIETE = "07";
    public static final String TIPO = "tipo";
    public static final String GUION = "-";
    public static final String COD_EMPRESA = "codEmpresa";
    public static final String PATH_SIGNATURE = "pathSignature";
    public static final String PASS_SIGNATURE = "passSignature";
    public static final String URL_RECEPCION = "urlRecepcion";
    public static final String SOAP_MESSAGE = "soapMessage";
    public static final String CLAVE_ACCESO = "claveAcceso";
    public static final String MENSAJES = "mensajes";
    public static final String IDENTIFICADOR = "identificador";
    public static final String MENSAJE = "mensaje";
    public static final String INFORMACION_ADICIONAL = "informacionAdicional";
    public static final String DEVUELTA = "DEVUELTA";
    public static final String URL_REPORTE = "urlReporte";
    public static final String LOTE = "lote";
    public static final String SPACE = " ";
    public static final String DATE_FORMAT_1 = "EEE MMM d HH:mm:ss yyyy";
    public static final String DATE_FORMAT_2 = "dd-MM-yyyy HH:mm:ss";
    public static final String AUTORIZADO = "AUTORIZADO";
    public static final String EN_PROCESAMIENTO = "EN PROCESAMIENTO";

    // Tablas
    public static final String FAC_FACTURA_C = "FAC_FACTURA_C";
    public static final String FAC_DEVOLUCION_C = "FAC_DEVOLUCION_C";
    public static final String PED_DESPACHO_C = "PED_DESPACHO_C";
    public static final String BAN_RETENCION_C = "BAN_RETENCION_C";
    public static final String CXC_DOC_COBRAR = "CXC_DOC_COBRAR";

    // Columnas
    public static final String SECUENCIAL = "SECUENCIAL";
    public static final String NUM_SECUENCIAL = "NUM_SECUENCIAL";
    public static final String NUM_FACTURA_INTERNO = "NUM_FACTURA_INTERNO";
    public static final String DIRECCION_COMPRADOR = "DIRECCION_COMPRADOR";
    public static final String TELEFONO_COMPRADOR = "TELEFONO_COMPRADOR";
    public static final String EMAIL_COMPRADOR = "EMAIL_COMPRADOR";
    public static final String OBSERVACION = "OBSERVACION";
    public static final String CONTRIBUYENTE_ESPECIAL = "CONTRIBUYENTE_ESPECIAL";
    public static final String DIRECCION_ESTABLECIMIENTO = "DIRECCION_ESTABLECIMIENTO";
    public static final String FECHA_FACTURA = "FECHA_FACTURA";
    public static final String IDENTIFICACION_COMPRADOR = "IDENTIFICACION_COMPRADOR";
    public static final String IMPORTE_TOTAL = "IMPORTE_TOTAL";
    public static final String MONEDA = "MONEDA";
    public static final String LLEVA_CONTABILIDAD = "LLEVA_CONTABILIDAD";
    public static final String PROPINA = "PROPINA";
    public static final String RAZON_SOCIAL_COMPRADOR = "RAZON_SOCIAL_COMPRADOR";
    public static final String TIPO_IDENTIFICACION_COMPRADOR = "TIPO_IDENTIFICACION_COMPRADOR";
    public static final String BASE_IMPONIBLE = "BASE_IMPONIBLE";
    public static final String CODIGO_IMPUESTO = "CODIGO_IMPUESTO";
    public static final String CODIGO_PORCENTAJE = "CODIGO_PORCENTAJE";
    public static final String CODIGO_PORCENTAJE_TXT = "CODIGO_PORCENTAJE_TXT";
    public static final String VALOR = "VALOR";
    public static final String BASE_IMPONIBLE_SIN_IVA = "BASE_IMPONIBLE_SIN_IVA";
    public static final String CODIGO_IMPUESTO_SIN_IVA = "CODIGO_IMPUESTO_SIN_IVA";
    public static final String CODIGO_PORCENTAJE_SIN_IVA = "CODIGO_PORCENTAJE_SIN_IVA";
    public static final String TARIFA_IVA_SIN_IVA = "TARIFA_IVA_SIN_IVA";
    public static final String VALOR_IVA_SIN_IVA = "VALOR_IVA_SIN_IVA";
    public static final String TOTAL_DESCUENTOS = "TOTAL_DESCUENTOS";
    public static final String TOTAL_SIN_IMPUESTOS = "TOTAL_SIN_IMPUESTOS";
    public static final String TOTAL_SUBSIDIO = "TOTAL_SUBSIDIO";
    public static final String CODIGO = "CODIGO";
    public static final String PLAZO = "PLAZO";
    public static final String VALOR_FORMA_PAGO = "VALOR_FORMA_PAGO";
    public static final String TIEMPO = "TIEMPO";
    public static final String COD_DOCUMENTO = "COD_DOCUMENTO";
    public static final String DIRECCION_MATRIZ = "DIRECCION_MATRIZ";
    public static final String ESTABLECIMIENTO = "ESTABLECIMIENTO";
    public static final String NOMBRE_COMERCIAL = "NOMBRE_COMERCIAL";
    public static final String PUNTO_EMISION = "PUNTO_EMISION";
    public static final String RAZON_SOCIAL_EMPRESA = "RAZON_SOCIAL_EMPRESA";
    public static final String RUC_EMPRESA = "RUC_EMPRESA";
    public static final String CANTIDAD = "CANTIDAD";
    public static final String COD_ARTICULO = "COD_ARTICULO";
    public static final String NOMBRE_ARTICULO = "NOMBRE_ARTICULO";
    public static final String DESCUENTO = "DESCUENTO";
    public static final String TARIFA = "TARIFA";
    public static final String PRECIO_SIN_SUBSIDIO = "PRECIO_SIN_SUBSIDIO";
    public static final String PRECIO_TOTAL_SIN_IMPUESTOS = "PRECIO_TOTAL_SIN_IMPUESTOS";
    public static final String PRECIO_UNITARIO = "PRECIO_UNITARIO";
    public static final String FECHA_EMISION = "FECHA_EMISION";
    public static final String RISE = "RISE";
    public static final String COD_DOC_MODIFICADO = "COD_DOC_MODIFICADO";
    public static final String NUM_DOC_MODIFICADO = "NUM_DOC_MODIFICADO";
    public static final String FECHA_EMISION_DOCSUSTENTO = "FECHA_EMISION_DOCSUSTENTO";
    public static final String VALOR_MODIFICADO = "VALOR_MODIFICADO";
    public static final String MOTIVO = "MOTIVO";
    public static final String NUM_DOCUMENTO_INTERNO = "NUM_DOCUMENTO_INTERNO";
    public static final String VALOR_TOTAL = "VALOR_TOTAL";
    public static final String FORMA_PAGO = "FORMA_PAGO";
    public static final String RAZON = "RAZON";
    public static final String DIRECCION = "DIRECCION";
    public static final String TELEFONO = "TELEFONO";
    public static final String NUM_DESPACHO_INTERNO = "NUM_DESPACHO_INTERNO";
    public static final String DIR_PARTIDA = "DIR_PARTIDA";
    public static final String RAZON_SOCIAL_TRANSPORTISTA = "RAZON_SOCIAL_TRANSPORTISTA";
    public static final String TIPO_IDENT_TRANSPORTISTA = "TIPO_IDENT_TRANSPORTISTA";
    public static final String RUC_TRANSPORTISTA = "RUC_TRANSPORTISTA";
    public static final String FECHA_INICIO_TRANSPORTE = "FECHA_INICIO_TRANSPORTE";
    public static final String FECHA_FIN_TRANSPORTE = "FECHA_FIN_TRANSPORTE";
    public static final String PLACA = "PLACA";
    public static final String CODIGOINTERNO = "CODIGOINTERNO";
    public static final String DESCRIPCION = "DESCRIPCION";
    public static final String IDENTIFICACION_DESTINATARIO = "IDENTIFICACION_DESTINATARIO";
    public static final String DIRDESTINATARIO = "DIRDESTINATARIO";
    public static final String MOTIVOTRASLADO = "MOTIVOTRASLADO";
    public static final String DOCADUANEROUNICO = "DOCADUANEROUNICO";
    public static final String COD_ESTAB_DESTINO = "COD_ESTAB_DESTINO";
    public static final String RUTA = "RUTA";
    public static final String CODDOSUSTENTO = "CODDOSUSTENTO";
    public static final String NUMDOCSUSTENTO = "NUMDOCSUSTENTO";
    public static final String NUMAUTDOCSUSTENTO = "NUMAUTDOCSUSTENTO";
    public static final String FECHAEMISIONDOCSUSTENTO = "FECHAEMISIONDOCSUSTENTO";
    public static final String RAZONSOCIALDESTINATARIO = "RAZONSOCIALDESTINATARIO";
    public static final String TELDESTINATARIO = "TELDESTINATARIO";
    public static final String MAILDESTINATARIO = "MAILDESTINATARIO";
    public static final String BASEIMPONIBLE = "BASEIMPONIBLE";
    public static final String CODDOCSUSTENTO = "CODDOCSUSTENTO";
    public static final String CODIGORETENCION = "CODIGORETENCION";
    public static final String PORCENTAJERETENR = "PORCENTAJERETENR";
    public static final String VALORRETENIDO = "VALORRETENIDO";
    public static final String DIRECCION_RETENIDO = "DIRECCION_RETENIDO";
    public static final String TELEFONO_RETENIDO = "TELEFONO_RETENIDO";
    public static final String EMAIL_RETENIDO = "EMAIL_RETENIDO";
    public static final String FECHA_RETENCION = "FECHA_RETENCION";
    public static final String IDENTIFICACION_SUJETO_RETENIDO = "IDENTIFICACION_SUJETO_RETENIDO";
    public static final String PERIODO_FISCAL = "PERIODO_FISCAL";
    public static final String RAZON_SOCIAL_SUJETO_RETENIDO = "RAZON_SOCIAL_SUJETO_RETENIDO";
    public static final String TIPO_IDENT_SUJETO_RETENIDO = "TIPO_IDENT_SUJETO_RETENIDO";

    public static final String FACTURA_C_SQL = "SELECT COD_EMPRESA, RUC_EMPRESA, RAZON_SOCIAL_EMPRESA, "
            + "NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_FACTURA_INTERNO, ESTABLECIMIENTO, "
            + "PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, DIRECCION_ESTABLECIMIENTO, "
            + "CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RAZON_SOCIAL_COMPRADOR, "
            + "FECHA_FACTURA, TIPO_IDENTIFICACION_COMPRADOR, IDENTIFICACION_COMPRADOR, "
            + "DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, EMAIL_COMPRADOR, "
            + "TOTAL_SIN_IMPUESTOS, TOTAL_DESCUENTOS, PROPINA, IMPORTE_TOTAL, "
            + "CLAVE_ACCESO, CODIGO_IMPUESTO, CODIGO_PORCENTAJE, BASE_IMPONIBLE, "
            + "VALOR, MONEDA, OBSERVACION, BASE_IMPONIBLE_SIN_IVA, CODIGO_IMPUESTO_SIN_IVA, "
            + "CODIGO_PORCENTAJE_SIN_IVA, TARIFA_IVA_SIN_IVA, VALOR_IVA_SIN_IVA, PLACA, TOTAL_SUBSIDIO "
            + "FROM ";

    public static final String FACTURA_C_SQL_MICROSOFT_SQL_SERVER = "SELECT TOP 20 COD_EMPRESA, RUC_EMPRESA, RAZON_SOCIAL_EMPRESA, "
            + "NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_FACTURA_INTERNO, ESTABLECIMIENTO, "
            + "PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, DIRECCION_ESTABLECIMIENTO, "
            + "CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RAZON_SOCIAL_COMPRADOR, "
            + "FECHA_FACTURA, TIPO_IDENTIFICACION_COMPRADOR, IDENTIFICACION_COMPRADOR, "
            + "DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, EMAIL_COMPRADOR, "
            + "TOTAL_SIN_IMPUESTOS, TOTAL_DESCUENTOS, PROPINA, IMPORTE_TOTAL, "
            + "CLAVE_ACCESO, CODIGO_IMPUESTO, CODIGO_PORCENTAJE, BASE_IMPONIBLE, "
            + "VALOR, MONEDA, OBSERVACION, BASE_IMPONIBLE_SIN_IVA, CODIGO_IMPUESTO_SIN_IVA, "
            + "CODIGO_PORCENTAJE_SIN_IVA, TARIFA_IVA_SIN_IVA, VALOR_IVA_SIN_IVA, PLACA, TOTAL_SUBSIDIO  "
            + "FROM ";

    public static final String FACTURA_D_SQL = "SELECT COD_EMPRESA, COD_DOCUMENTO, "
            + "NUM_DOCUMENTO_INTERNO, COD_ARTICULO, NOMBRE_ARTICULO, CANTIDAD, "
            + "PRECIO_UNITARIO, DESCUENTO, CODIGO_IMPUESTO, CODIGO_PORCENTAJE, TARIFA, "
            + "BASE_IMPONIBLE, VALOR, PRECIO_TOTAL_SIN_IMPUESTOS, PRECIO_SIN_SUBSIDIO "
            + "FROM V_FACTURA_ELECTRONICA_D "
            + "WHERE ";

    public static final String FACTURA_PAGO_SQL = "SELECT CODIGO, FORMA_PAGO, PLAZO, TIEMPO, "
            + "VALOR_FORMA_PAGO "
            + "FROM V_FACTURA_ELECTRONICA_PAGO "
            + "WHERE ";

    public static final String RETENCION_C_SQL_MYSQL = "SELECT COD_EMPRESA, RUC_EMPRESA, RAZON_SOCIAL_EMPRESA, "
            + "NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_RETENCION_INTERNO, CLAVE_ACCESO, "
            + "ESTABLECIMIENTO, PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, "
            + "RAZON_SOCIAL_SUJETO_RETENIDO, DIRECCION_RETENIDO, TELEFONO_RETENIDO, "
            + "EMAIL_RETENIDO, FECHA_RETENCION, TIPO_IDENT_SUJETO_RETENIDO, "
            + "IDENTIFICACION_SUJETO_RETENIDO, PERIODO_FISCAL, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE "
            + "FROM V_RETENCION_ELECTRONICA_C "
            + "WHERE ";

    public static final String RETENCION_C_SQL_ORACLE = "SELECT COD_EMPRESA, RUC_EMPRESA, RAZON_SOCIAL_EMPRESA, "
            + "NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_RETENCION_INTERNO, CLAVE_ACCESO, "
            + "ESTABLECIMIENTO, PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, "
            + "RAZON_SOCIAL_SUJETO_RETENIDO, DIRECCION_RETENIDO, TELEFONO_RETENIDO, "
            + "EMAIL_RETENIDO, FECHA_RETENCION, TIPO_IDENT_SUJETO_RETENIDO, "
            + "IDENTIFICACION_SUJETO_RETENIDO, PERIODO_FISCAL, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE "
            + "FROM V_RETENCION_ELECTRONICA_C "
            + "WHERE ";

    public static final String RETENCION_C_SQL_MICROSOFT_SQL_SERVER = "SELECT TOP 20 COD_EMPRESA, RUC_EMPRESA, RAZON_SOCIAL_EMPRESA, "
            + "NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_RETENCION_INTERNO, CLAVE_ACCESO, "
            + "ESTABLECIMIENTO, PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, "
            + "RAZON_SOCIAL_SUJETO_RETENIDO, DIRECCION_RETENIDO, TELEFONO_RETENIDO, "
            + "EMAIL_RETENIDO, FECHA_RETENCION, TIPO_IDENT_SUJETO_RETENIDO, "
            + "IDENTIFICACION_SUJETO_RETENIDO, PERIODO_FISCAL, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE "
            + "FROM V_RETENCION_ELECTRONICA_C "
            + "WHERE ";

    public static final String RETENCION_D_SQL = "SELECT CODIGO, CODIGORETENCION, "
            + "BASEIMPONIBLE, PORCENTAJERETENR, VALORRETENIDO, CODDOCSUSTENTO, "
            + "NUMDOCSUSTENTO, FECHAEMISIONDOCSUSTENTO "
            + "FROM V_RETENCION_ELECTRONICA_D "
            + "WHERE ";

    public static final String NOTA_CREDITO_C_SQL_MYSQL = "SELECT COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_FACTURA_INTERNO, "
            + "CLAVE_ACCESO, ESTABLECIMIENTO, PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RISE, "
            + "RAZON_SOCIAL_COMPRADOR, DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, "
            + "EMAIL_COMPRADOR, OBSERVACION, FECHA_EMISION, TIPO_IDENTIFICACION_COMPRADOR, "
            + "IDENTIFICACION_COMPRADOR, COD_DOC_MODIFICADO, NUM_DOC_MODIFICADO, "
            + "FECHA_EMISION_DOCSUSTENTO, VALOR_MODIFICADO, TOTAL_SIN_IMPUESTOS, "
            + "MOTIVO, TOTAL_DESCUENTOS, PROPINA, IMPORTE_TOTAL, CODIGO_IMPUESTO, "
            + "CODIGO_PORCENTAJE, BASE_IMPONIBLE, VALOR, MONEDA, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE "
            + "FROM V_NOTA_CREDITO_ELECTRONICA_C "
            + "WHERE ";

    public static final String NOTA_CREDITO_C_SQL_ORACLE = "SELECT COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_FACTURA_INTERNO, "
            + "CLAVE_ACCESO, ESTABLECIMIENTO, PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RISE, "
            + "RAZON_SOCIAL_COMPRADOR, DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, "
            + "EMAIL_COMPRADOR, OBSERVACION, FECHA_EMISION, TIPO_IDENTIFICACION_COMPRADOR, "
            + "IDENTIFICACION_COMPRADOR, COD_DOC_MODIFICADO, NUM_DOC_MODIFICADO, "
            + "FECHA_EMISION_DOCSUSTENTO, VALOR_MODIFICADO, TOTAL_SIN_IMPUESTOS, "
            + "MOTIVO, TOTAL_DESCUENTOS, PROPINA, IMPORTE_TOTAL, CODIGO_IMPUESTO, "
            + "CODIGO_PORCENTAJE, BASE_IMPONIBLE, VALOR, MONEDA, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE "
            + "FROM V_NOTA_CREDITO_ELECTRONICA_C "
            + "WHERE ";

    public static final String NOTA_CREDITO_C_SQL_MICROSOFT_SQL_SERVER  = "SELECT TOP 20 COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, NUM_FACTURA_INTERNO, "
            + "CLAVE_ACCESO, ESTABLECIMIENTO, PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RISE, "
            + "RAZON_SOCIAL_COMPRADOR, DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, "
            + "EMAIL_COMPRADOR, OBSERVACION, FECHA_EMISION, TIPO_IDENTIFICACION_COMPRADOR, "
            + "IDENTIFICACION_COMPRADOR, COD_DOC_MODIFICADO, NUM_DOC_MODIFICADO, "
            + "FECHA_EMISION_DOCSUSTENTO, VALOR_MODIFICADO, TOTAL_SIN_IMPUESTOS, "
            + "MOTIVO, TOTAL_DESCUENTOS, PROPINA, IMPORTE_TOTAL, CODIGO_IMPUESTO, "
            + "CODIGO_PORCENTAJE, BASE_IMPONIBLE, VALOR, MONEDA, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE "
            + "FROM V_NOTA_CREDITO_ELECTRONICA_C "
            + "WHERE ";

    public static final String NOTA_CREDITO_D_SQL = "SELECT COD_EMPRESA, COD_DOCUMENTO, "
            + "NUM_DOCUMENTO_INTERNO, COD_ARTICULO, NOMBRE_ARTICULO, CANTIDAD, "
            + "PRECIO_UNITARIO, DESCUENTO, CODIGO_IMPUESTO, CODIGO_PORCENTAJE, TARIFA, "
            + "BASE_IMPONIBLE, VALOR, PRECIO_TOTAL_SIN_IMPUESTOS "
            + "FROM V_NOTA_CREDITO_ELECTRONICA_D "
            + "WHERE ";

    public static final String NOTA_DEBITO_C_SQL_MYSQL = "SELECT COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, "
            + "NUM_DOCUMENTO_INTERNO, CLAVE_ACCESO, ESTABLECIMIENTO, "
            + "PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, "
            + "LLEVA_CONTABILIDAD, RISE, RAZON_SOCIAL_COMPRADOR, "
            + "DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, EMAIL_COMPRADOR, "
            + "RAZON, FECHA_EMISION, TIPO_IDENTIFICACION_COMPRADOR, "
            + "IDENTIFICACION_COMPRADOR, COD_DOC_MODIFICADO, NUM_DOC_MODIFICADO, "
            + "FECHA_EMISION_DOCSUSTENTO, TOTAL_SIN_IMPUESTOS, CODIGO_IMPUESTO, "
            + "CODIGO_PORCENTAJE, TARIFA, BASE_IMPONIBLE, VALOR, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE, VALOR_TOTAL "
            + "FROM V_NOTA_DEBITO_ELECTRONICA_C "
            + "WHERE ";

    public static final String NOTA_DEBITO_C_SQL_ORACLE = "SELECT COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, "
            + "NUM_DOCUMENTO_INTERNO, CLAVE_ACCESO, ESTABLECIMIENTO, "
            + "PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, "
            + "LLEVA_CONTABILIDAD, RISE, RAZON_SOCIAL_COMPRADOR, "
            + "DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, EMAIL_COMPRADOR, "
            + "RAZON, FECHA_EMISION, TIPO_IDENTIFICACION_COMPRADOR, "
            + "IDENTIFICACION_COMPRADOR, COD_DOC_MODIFICADO, NUM_DOC_MODIFICADO, "
            + "FECHA_EMISION_DOCSUSTENTO, TOTAL_SIN_IMPUESTOS, CODIGO_IMPUESTO, "
            + "CODIGO_PORCENTAJE, TARIFA, BASE_IMPONIBLE, VALOR, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE, VALOR_TOTAL "
            + "FROM V_NOTA_DEBITO_ELECTRONICA_C "
            + "WHERE ";

    public static final String NOTA_DEBITO_C_SQL_MICROSOFT_SQL_SERVER = "SELECT TOP 20 COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, "
            + "NUM_DOCUMENTO_INTERNO, CLAVE_ACCESO, ESTABLECIMIENTO, "
            + "PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, "
            + "DIRECCION_ESTABLECIMIENTO, CONTRIBUYENTE_ESPECIAL, "
            + "LLEVA_CONTABILIDAD, RISE, RAZON_SOCIAL_COMPRADOR, "
            + "DIRECCION_COMPRADOR, TELEFONO_COMPRADOR, EMAIL_COMPRADOR, "
            + "RAZON, FECHA_EMISION, TIPO_IDENTIFICACION_COMPRADOR, "
            + "IDENTIFICACION_COMPRADOR, COD_DOC_MODIFICADO, NUM_DOC_MODIFICADO, "
            + "FECHA_EMISION_DOCSUSTENTO, TOTAL_SIN_IMPUESTOS, CODIGO_IMPUESTO, "
            + "CODIGO_PORCENTAJE, TARIFA, BASE_IMPONIBLE, VALOR, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE, VALOR_TOTAL "
            + "FROM V_NOTA_DEBITO_ELECTRONICA_C "
            + "WHERE ";

    public static final String NOTA_DEBITO_PAGO_SQL = "SELECT COD_EMPRESA, "
            + "NUM_DOCUMENTO_INTERNO, CODIGO, FORMA_PAGO, PLAZO, TIEMPO, VALOR_FORMA_PAGO "
            + "FROM V_NOTA_DEBITO_ELECTRONICA_PAGO "
            + "WHERE ";

    public static final String GUIA_REMISION_C_SQL = "SELECT COD_EMPRESA, RUC_EMPRESA, "
            + "RAZON_SOCIAL_EMPRESA, NOMBRE_COMERCIAL, COD_DOCUMENTO, "
            + "NUM_DESPACHO_INTERNO, CLAVE_ACCESO, ESTABLECIMIENTO, "
            + "PUNTO_EMISION, SECUENCIAL, DIRECCION_MATRIZ, DIRECCION_ESTABLECIMIENTO, "
            + "CONTRIBUYENTE_ESPECIAL, LLEVA_CONTABILIDAD, RAZON_SOCIAL_TRANSPORTISTA, "
            + "TIPO_IDENT_TRANSPORTISTA, RUC_TRANSPORTISTA, RISE, DIR_PARTIDA, "
            + "FECHA_INICIO_TRANSPORTE, FECHA_FIN_TRANSPORTE, PLACA, ESTADO_SRI, "
            + "CLAVE_ACCESO_LOTE "
            + "FROM V_GUIA_REMISION_ELECTRONICA_C "
            + "WHERE ";

    public static final String GUIA_REMISION_D_SQL = "SELECT NUM_DESPACHO_INTERNO, "
            + "IDENTIFICACION_DESTINATARIO, RAZONSOCIALDESTINATARIO, DIRDESTINATARIO, "
            + "TELDESTINATARIO, MAILDESTINATARIO, MOTIVOTRASLADO, DOCADUANEROUNICO, "
            + "RUTA, COD_ESTAB_DESTINO, CODDOSUSTENTO, NUMDOCSUSTENTO, NUMAUTDOCSUSTENTO, "
            + "FECHAEMISIONDOCSUSTENTO "
            + "FROM V_GUIA_REMISION_ELECTRONICA_D "
            + "WHERE ";

    public static final String GUIA_REMISION_ARTICULO_SQL = "SELECT NUM_DESPACHO_INTERNO, "
            + "CODIGOINTERNO, DESCRIPCION, CANTIDAD, DETALLEADICIONAL1, DETALLEADICIONAL2 "
            + "FROM V_GUIA_REMISION_ARTICULO "
            + "WHERE ";

}